-- stolen from https://github.com/KevinPalowa/nvim/

require("chandra.options")
require("chandra.autocmds")
require("chandra.keymaps")
require("chandra.plugins")
require("chandra.colorscheme")
require("chandra.cmp")
require("chandra.lsp")
require("chandra.telescope")
require("chandra.presence")
require("chandra.toggleterm")
require("chandra.lualine")
require("chandra.autopairs")
require("chandra.comment")
require("chandra.gitsigns")
require("chandra.nvimtree")
require("chandra.treesitter")
require("chandra.bufferline")
require("chandra.indentline")
require("chandra.alpha")
require("chandra.project")
require("chandra.colorizer")
require("chandra.whichkey")
